# Generated by Django 3.0.6 on 2020-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('campaign_img', models.URLField()),
                ('campaign_content', models.TextField()),
                ('campaign_price', models.IntegerField()),
                ('campaign_people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=8)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=64)),
                ('now_funding', models.IntegerField()),
                ('funding_target', models.IntegerField()),
                ('donator', models.IntegerField()),
                ('timeline', models.CharField(max_length=64)),
                ('residual_time', models.IntegerField()),
                ('status', models.CharField(max_length=8)),
                ('url', models.URLField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=64)),
                ('proj_type', models.CharField(max_length=16)),
                ('proj_funding_target', models.IntegerField()),
                ('proj_duration', models.IntegerField()),
                ('proj_campaign_num', models.IntegerField()),
                ('proj_description', models.TextField()),
                ('proj_add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
