# Generated by Django 3.0.6 on 2020-08-29 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200824_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='channel',
            field=models.CharField(default='unknown', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Project'),
        ),
    ]
