# Generated by Django 3.0.6 on 2020-08-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200829_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='id',
        ),
    ]
