# Generated by Django 3.0.6 on 2020-08-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200829_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='residual_time',
            field=models.CharField(max_length=16),
        ),
    ]
