# Generated by Django 3.0.6 on 2020-08-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200829_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
